### ISSUE TITLE
Raspberry Pi 2

### ISSUE THREAD

**Issue by xbmcnut** [LS80/script.openelec.rpi.config#6]
Any plans to support the new Pi 2 board?

**Comment by LS80** [comment]
Yes I will release a new version soon.

**Comment by LS80** [comment]
Are you able to test this on a Pi 2? I don't have one yet
https://www.dropbox.com/s/1839g4xwjv4covd/script.openelec.rpi.config-0.19.0.zip

Can you see the setting for "Output the maximum 1.2A from USB ports (max_usb_current)"?

**Comment by Mafarricos** [comment]
This version will have default OC values to RPi2 as also to RPi? Or the default OC values are the same in both RPi's?
Supposedly RPi2 will manage higher OC values, no?

**Comment by LS80** [comment]
It seems that RPi 2 has similar overclock headroom from what I've seen posted. I'll revisit the preset settings at a later date once things become clearer.

Closing for now.

**Comment by xbmcnut** [comment]
Seems to work fine on PI 2, thank you. 1.2A output setting visible too.
